# thinkpython-python3
# ver 0.3

FROM ubuntu:14.04
RUN apt-get -q update && apt-get install -y \
    python3-setuptools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN easy_install3 pip
RUN pip install virtualenv

VOLUME ["/src/ThinkPython"]

WORKDIR /workspace

RUN virtualenv python3-env
