# thinkpython-pypy
# ver 0.3

FROM ubuntu:14.04
#RUN apt-get update -q && apt-get install -y software-properties-common
#RUN add-apt-repository ppa:pypy/ppa
RUN apt-get -q update && apt-get install -y \
    wget \
    python-setuptools \
#    pypy \
#    pypy-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN wget https://bitbucket.org/pypy/pypy/downloads/pypy-5.1.1-linux64.tar.bz2 -P /tmp
RUN tar -xjvf /tmp/pypy-5.1.1-linux64.tar.bz2 -C /opt/
RUN rm -f /tmp/pypy-5.1.1-linux64.tar.bz2
RUN easy_install pip
RUN pip install virtualenv

VOLUME ["/src/ThinkPython"]

WORKDIR /workspace

RUN virtualenv -p /opt/pypy-5.1.1-linux64/bin/pypy pypy-env
