# thinkpython-python2
# ver 0.3

FROM ubuntu:14.04
RUN apt-get -q update && apt-get install -y \
    python-setuptools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN easy_install pip
RUN pip install virtualenv

VOLUME ["/src/ThinkPython"]

WORKDIR /workspace

RUN virtualenv python2-env
